# Generated by Django 5.0.1 on 2024-02-04 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('overnight_stay', models.BooleanField(default=False)),
                ('food_preferences', models.CharField(blank=True, choices=[('none', 'Keine'), ('vegetarian', 'Vegetarisch'), ('vegan', 'Vegan')], default='none', max_length=64)),
                ('link_identifier', models.CharField(blank=True, editable=False, max_length=128, unique=True)),
                ('note', models.TextField(blank=True)),
                ('visited', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gast',
                'verbose_name_plural': 'Gäste',
            },
        ),
        migrations.CreateModel(
            name='Entourage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('overnight_stay', models.BooleanField(default=False)),
                ('food_preferences', models.CharField(blank=True, choices=[('none', 'Keine'), ('vegetarian', 'Vegetarisch'), ('vegan', 'Vegan')], default='none', max_length=64)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_manager.guest')),
            ],
            options={
                'verbose_name': 'Begleitung',
                'verbose_name_plural': 'Begleitung',
            },
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='content-images')),
                ('order', models.IntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='invitation_manager.content')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
