# Generated by Django 5.0.1 on 2024-02-04 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='content-images')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('overnight_stay', models.BooleanField(default=False)),
                ('food_preferences', models.CharField(choices=[('none', 'Keine'), ('vegetarian', 'Vegetarisch'), ('vegan', 'Vegan')], default='none', max_length=64)),
                ('link_identifier', models.CharField(blank=True, editable=False, max_length=128, unique=True)),
                ('note', models.TextField(blank=True)),
                ('visited', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gast',
                'verbose_name_plural': 'Gäste',
            },
        ),
        migrations.CreateModel(
            name='Entourage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('overnight_stay', models.BooleanField(default=False)),
                ('food_preferences', models.CharField(choices=[('none', 'Keine'), ('vegetarian', 'Vegetarisch'), ('vegan', 'Vegan')], default='none', max_length=64)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_manager.guest')),
            ],
            options={
                'verbose_name': 'Begleitung',
                'verbose_name_plural': 'Begleitung',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(blank=True)),
                ('subheader', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_manager.event')),
                ('images', models.ManyToManyField(blank=True, to='invitation_manager.imagefile')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('text', models.TextField(blank=True)),
                ('arrival_description', models.TextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invitation_manager.imagefile')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_manager.location'),
        ),
    ]
