# Generated by Django 5.0.1 on 2024-02-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='visited',
            new_name='confirmed',
        ),
    ]
