# Generated by Django 5.0.1 on 2024-02-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entourage',
            name='food_preferences',
            field=models.CharField(choices=[('none', 'Keine'), ('vegetarian', 'Vegetarisch'), ('vegan', 'Vegan')], default='none', max_length=64),
        ),
        migrations.AlterField(
            model_name='guest',
            name='food_preferences',
            field=models.CharField(choices=[('none', 'Keine'), ('vegetarian', 'Vegetarisch'), ('vegan', 'Vegan')], default='none', max_length=64),
        ),
    ]
