# Generated by Django 5.0.1 on 2024-02-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagefile',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='imagefile',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
