# Generated by Django 5.0.1 on 2024-02-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='entourage',
            name='food_preferences',
            field=models.CharField(blank=True, choices=[('', 'Keine'), ('vegetarian', 'Vegetarisch'), ('vegan', 'Vegan')], default=('', 'Keine'), max_length=64),
        ),
        migrations.AlterField(
            model_name='guest',
            name='food_preferences',
            field=models.CharField(blank=True, choices=[('', 'Keine'), ('vegetarian', 'Vegetarisch'), ('vegan', 'Vegan')], default=('', 'Keine'), max_length=64),
        ),
        migrations.AlterField(
            model_name='guest',
            name='link_identifier',
            field=models.CharField(blank=True, editable=False, max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='content-images')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='invitation_manager.content')),
            ],
        ),
    ]
