# Generated by Django 5.0.1 on 2024-02-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_manager', '0002_rename_visited_guest_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='confirmed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='visited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
